import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FaCog } from "react-icons/fa";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header>
            <div className="container flex items-center gap-12 py-4">
              <Link href={"/"}>Home</Link>
              <Link href={"/settings"} className="flex items-center gap-2">
                Setări
                <FaCog />
              </Link>
            </div>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
